### ISSUE TITLE
ScNapBar error

### ISSUE THREAD

**Issue by bbhatt1789** [dieterich-lab/single-cell-nanopore#10]
Hello. I was able to install, compile, get into condo environment and all. Do I need to also install Flexbar? May be I am doing something wrong. It says :

 singleCellPipe possorted_genome_bam.bam - w /storage/chenseq/oxford_nano/data/10x3_Lobe_D009_13_NeuN_outs/filtered_feature_bc_matrix/barcodes.tsv -rf /storage/chen/Pipeline/pipeline/pipeline_restructure/reference/hg19/Homo_sapiens.GRCh37.75.gtf
-bash: singleCellPipe: command not found

**Comment by qwang-big** [comment]
hi, have you tried compiling the *singleCellPipe* after installation? You can find the following necessary steps 3&4 in the installation guide
```
3. Change working directory into the new single-cell-nanopore folder
cd single-cell-nanopore
4. Use these commands for building ScNapBar:
cmake .
make
```

**Comment by bbhatt1789** [comment]
Yes I have. And I am also able to start the condo environment for this,

> hi, have you tried compiling the _singleCellPipe_ after installation? You can find the following necessary steps 3&4 in the installation guide
> 
> ```
> 3. Change working directory into the new single-cell-nanopore folder
> cd single-cell-nanopore
> 4. Use these commands for building ScNapBar:
> cmake .
> make
> ```

**Comment by bbhatt1789** [comment]
Yes I have it works fine. I can also initialize the condo environment using:

conda activate single-cell-nanopore

That works.
