### ISSUE TITLE
ScNapBar: minor bugs, improvements, questions.

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/single-cell-nanopore#11]
I am recording in this single issue minor bugs and questions I encountered as a first time user of **ScNapBar**. I also add a few suggestions, in particular regarding _testing_.

## bugs

- in Snakefile, under rule `assign_gene`, the output path is incomplete, and should read `genes = dir_out + 'Nanopore.ge'`, this causes missing file errors when running `snakemake --until run_umi_seq`.
- in Snakefile, `rm {params.prefix}.tab {params.prefix}.fasta {params.prefix}parameterLog.log` has to be changed to 
`rm {params.prefix}.tab {params.prefix}.fasta {params.prefix}_paramLog.log`, otherwise this will cause a runtime error.

## Improvements/suggestions

- The repo should include a .gitignore to ignore all build/compilation-related and tmp files to allow a smooth git workflow. I also think that the Snakefile/config template should be adjusted to avoid hard-coded paths, _etc._ and allow to specify the location of scripts/executable without having to run the pipeline inside the repo, and thus cluttering it with input/output and tmp files.
- There are currently no tests, and not even reference output files for comparing output from a fresh install. The suggested example (_for testing purposes, we suggest downloading the GSE130708 dataset_) is not enough documented to be useful, and it is unclear if this is in any way related to the files under data/? _e.g._ the template config file refers to human data, but the suggested example consists of mouse data. Besides, shouldn't the barcodes file under data/ be named raw.tsv.gz? And the downsampled bam file, what is it? In summary, it is really difficult to get started, unless one wants to run **ScNapBar** on a full dataset without knowing what to expect.
- The description of output files is confusing, and does not differentiate option 1 and option 2 (output files differ). Similarly, the section _Step-by-step instructions_ appears to be only for option 1.
- Some parameters would benefit from a better description, define default values and/or suggested values for standard use-case scenarios, e.g. `polyTlength`, `numSimReads`, etc.
- Some tmp files are not removed, e.g. whitelist.fa.tmp.

## Questions/remarks

- Under pipelines/ there are 2 .md files with snippets of undocumented code... difficult to figure out what this is used for.

**Comment by qwang-big** [comment]
Hi Etienne,

I really appreciate your efforts in testing ScNapBar, I've currently fixed the bugs/remarks in the repo. The improvements take some time to complete, but a small dummy dataset would be really helpful as you suggested, which is currently not included in the pipeline.

Best, Qi

**Comment by eboileau** [comment]
Thanks @qwang-big  for your prompt feedback. I think clarifying the _testing issue_ and the parameters description (with tested default values) is important for reproducibility. I can eventually take care of other minor improvements when time permits.

For testing data, why not using part of the benchmark data that was used in the paper for the simulation study, say at 50% saturation (Fig 2 barcode assignment with UMI matches and without UMI matches)? Is this data still available? To be useful as a quick test run, all input files should be readily available (e.g. fastq, bam, annotation, etc.), config, as well as the final output (labels, etc. for both option 1 and 2) for comparison. What do you think?

The description/documentation I can take care afterwards, if you wish.

**Comment by qwang-big** [comment]
Hi Etienne,

Thank you very much for the help. I think we can use our own data for testing since the paper has already been published. However, I couldn't find the data from the accession number in the paper 
https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA722142. Because I've already deleted the data in my home folder on the cluster. It would be nice if you can prepare some testing data by sampling 10% or even less from the original data. Then we can run the pipeline and put the sample data somewhere, e.g. a separate repo for hosting.  

Best, Qi

**Comment by CDieterich** [comment]
Dear @qwang-big and @eboileau 

I have asked for immediate release of 
BioProject: PRJNA722142
at NCBI SRA.

**Comment by CDieterich** [comment]
Dear @qwang-big ,

please specify what the data under: repository/single-cell-nanopore/data is used for.
It should be easy to simulate a test data set (with NanoSim).

**Comment by qwang-big** [comment]
Hi @CDieterich and @eboileau ,

I've uploaded the reads extracted from chr17 of the dataset in the paper, which contains SRSF2 gene which exhibits differential isoforms. You can run Snakemake with the dataset to verifiy the correctness of the pipeline. I also attached the SRSF2 reads extracted from FC1 in the `analysis` folder for your reference. If there are other bugs/improvements, please feel free to correct them. Thanks!

Best, Qi

**Comment by eboileau** [comment]
Dear @qwang-big 

Thanks for adding the necessary files to run the example.
The pipeline runs fine, except that:

- in Snakefile, `rm {params.prefix}.tab {params.prefix}.fasta {params.prefix}parameterLog.log` has to be changed to
`rm {params.prefix}.tab {params.prefix}.fasta {params.prefix}_paramLog.log`, otherwise this will cause a runtime error.
This was changed at line 269, but also needs to be changed at line 298.

I think results make sense, although the final output _real.label_ differ with that under analysis/, which is expected
since the simulated data will differ. **If this should not be the case, please comment**. 

But I have a few more questions:

- What is the file Nanopore.GE.bam on the repository? It does not match anything... _i.e._ the output of the pipeline 
should be Nanopore.bam, right?
- How can we use the files SRSF2.GFP+/-.bam? _i.e._ is it useful for comparison? I understand that we would need the GFP labels from the Illumina to extract these...?

Now, this was for option 1. I also tried running option 2, but the final output files (output of `run_umi_gene` and `run_umi_seq`) are empty:

Nanopore.ge
Nanopore.geneumi
real.umi

**Given the test data, is that expected?** I thought this was also used in the paper?

**Comment by qwang-big** [comment]
Dear @eboileau 

Because the simulated reads differ each time, it is expected if you get slightly different barcode assignment scores
> I think results make sense, although the final output _real.label_ differ with that under analysis/, which is expected
> since the simulated data will differ. **If this should not be the case, please comment**.

This is the same Nanopore.bam with GE tag (gene assignment) done by `TagReadWithGeneExon.jar`
> * What is the file Nanopore.GE.bam on the repository? It does not match anything... _i.e._ the output of the pipeline
>   should be Nanopore.bam, right?

The GFP barcodes can be identified from Illumina reads, but these results are unrelavent to this pipleline. I just put them here since they are extremely small. 
> * How can we use the files SRSF2.GFP+/-.bam? _i.e._ is it useful for comparison? I understand that we would need the GFP labels from the Illumina to extract these...?

I test option 2 without your aforementioned problems, please make sure you have renamed the anntation file to hg38.refFlat (must have .refFlat extension) and the chromosome IDs match the chromosome IDs in the bam files (be aware of the **chr** prefix in their IDs).  
> Now, this was for option 1. I also tried running option 2, but the final output files (output of `run_umi_gene` and `run_umi_seq`) are empty:

In case you still have problem in troubleshooting these, hereby I attached the command lines used in **option 2**:
```sh
samtools view data/possorted_genome_bam.bam|perl -ne 'print "$2\t$3\t$1\n" if /GN:Z:(\S+).*CB:Z:([ACGT]+).*UB:Z:([ACGT]+)/'|sort|uniq > analysis/Illu.ge
java -jar -Xmx64g TagReadWithGeneExon.jar I=analysis/Nanopore.bam O=tmpge.bam ANNOTATIONS_FILE=data/hg38.refFlat ALLOW_MULTI_GENE_READS=true USE_STRAND_INFO=true
samtools view tmpge.bam |perl -F"\t" -ane 'print "$F[0]\t$1\n" if /GE:Z:(\w+)/' > analysis/Nanopore.ge
perl pipelines/get_gene_umi.pl analysis/real_umi.fasta analysis/Nanopore.ge > analysis/Nanopore.geneumi
mkdir tmpd
perl pipelines/umialign.pl analysis/Illu.ge analysis/Nanopore.geneumi x 10 tmpd > analysis/real.umi
```
> Nanopore.ge
> Nanopore.geneumi
> real.umi
> 
> **Given the test data, is that expected?** I thought this was also used in the paper?

**Comment by eboileau** [comment]
Thanks for your reply. As for option 2, indeed this was due to the _chr_ in the refFlat file. I guess your latest commit addresses this, but note that link in the README.md  _Annotation file in refFlat formats and .refFlat filename extension._  still points to
http://hgdownload.cse.ucsc.edu/goldenpath/mm10/database/refFlat.txt.gz.
