### ISSUE TITLE
BSD-3 licensed? A license file would be nice.

### ISSUE THREAD

**Issue by smoe** [dieterich-lab/single-cell-nanopore#8]
Hello,

Thank you for this work! With the exception of mummer 4 beta, we have all the dependencies listed in environment.yaml in Debian+Ubuntu, so I thought I should bring your software to Debian+Ubuntu ... and we finally have a motivation to also update MUMmer.

The BSD-3 reference I found in https://github.com/dieterich-lab/single-cell-nanopore/blob/master/src/Flexbar.cpp. No idea if this also holds for the remainder of this repository. There is an obvious exception for seqan (which you may want to remove from this source tree since both Debian and Conda also distribute it), and maybe also not for the other parts.

The last time I sent this kind of request I was surprised with a reply asking me to prepare a requestive license file as a  pull request. I would happily volunteer to do that. Just please send a quick instruction like "BSD-3 with the authors that are also in our preprint".

Many thanks and regards,
Steffen

**Comment by qwang-big** [comment]
Hi Steffen,

thank you very much for your suggestions. We now include a GPL-v3 licence file in this repo. We will move Flexbar into a sub-repo later. Please let us know if you have further questions in using our software. 

Best regards,
Qi Wang

**Comment by smoe** [comment]
Hi Qi,

Thank you for your swift reply. We need to generate the data first for deeper questions - have only just bought a MinION.
My initial short at Debian's copyright file is here https://salsa.debian.org/med-team/scnapbar/-/blob/master/debian/copyright . Ideally, as the GPL states, you have a reference to the GPL in every source file you want to put under that license. Also, the exact copyright holders are not clear. And if it is "version 3" or "version 3 or any later version" of that license.

I removed the seqan include directory and the .jar file from Debian's source tree, so the copyright declarations could be simplified. One of the next weeks will have me eventually follow your instructions in the README to finish the packaging.

Many thanks and best regards,
Steffen
